# Required for AI features
OPENAI_API_KEY = "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"

# Optional - for email verification
SMTP_USERNAME = "globuchi2@gmail.com"
SMTP_PASSWORD = "aepo klsj zuhi kwaf"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

# Optional - for payment processing
STRIPE_SECRET_KEY = "sk_test_51S1vn3JoBtcI8WkTvdyWnqASa48w62PEsAnnVgIBJDtXvoQ40cngWRitrDZ59Gv4S7w1fxqj8P4sAtPB0NviMtiy00XWa6K5eH"